djangonautic/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup")
]

djangonautic/articles/urls.py
####IMPORTANTE registrare l'app allinterno di settings del main project

# copiato incollato da urls di djangonautic

from django.conf.urls import url
from django.urls import path
from . import views            
 # . same dir


app_name= 'articles' #questo è per distingruere i nomi!!! cosi da fare articles:list o altro

urlpatterns = [
    
    url(r'^$',views.article_list, name = "list"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail, name = "detail"),  #questo è il modo per prendere la quesry nell url e passarla al "server"
    
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
# . same dir     
from . import views     
    # questo è per la parte statica Importante mettere nle SETTING
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  
from django.conf.urls.static import static
from django.conf import settings


 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/',include('articles.urls')),
     url(r'^accounts/',include('accounts.urls')),
    url(r'^about/$',views.about),
    url(r'^$',views.homepage),  
   
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) # per usare da un template

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models

# Create your models here.



class Article(models.Model):
    #questo è un modello e bisogna dare la MIGRAZIONE
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True) #per ogni cambiamento si da la migrazione
    # autore


#### how to do migrations   ####
    # manage.py makemigration
    # manage.py migrate

    def __str__(self):
         return self.title

    def snippet(self):
        return self.body[0:50] + '...'

djangonautic/accounts/views.py
from django.shortcuts import render


# Create your views here.
def signup_view(request):
    return render(request, 'accounts/signup.html')

djangonautic/articles/views.py
####IMPORTANTE registrare l'app allinterno di settings del main project

from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles':articles}) # pre farlo vedere registrarlo nell url principale 

def article_detail(request, slug):
   # return HttpResponse(slug)

   article = Article.objects.get(slug = slug)
   
   return render(request, 'articles/article_detail.html',{'article': article})

djangonautic/djangonautic/views.py
#prima cosa è importare
from django.http import HttpResponse
from django.shortcuts import render



###!!!! andare dentro settings e cercare per TEMPLATES nella sezione DIRS mettere la 'directory' delle pagine 

def homepage(request):
   # return HttpResponse('homepage')
   #retorn template e importiamo il modulo per reder
   return render(request,'homepage.html')

def about(request):
    #return HttpResponse('about')
     #retorn template e importiamo il modulo per reder
    return render(request,'about.html')

def project(request):
    return render(request,'./www/index.html')

djangonautic/accounts/templates/accounts/signup.html
{%  extends 'base_layout.html' %}

{% block content %}
<h1>SignUp</h1>
{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{article.thumb.url}}" alt=""/>
        <h2>{{article.title}}</h2>
            <p>{{article.body}}</p>
            <p>{{article.date}}</p>
        
    </div>

</div>


{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{%  extends 'base_layout.html' %}

{% block content %}
    <h1>Article list</h1>
    <div class="articles">
        {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>Body: {{ article.snippet }}</p>
            <p>Date: {{ article.date }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock %}    

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About us we like sjango </h1>
    <p>welcome to Djangonautic</p>
</body>
</html>

djangonautic/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>aticle</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
    <body>
        <div class="wrapper">
            <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}" alt=""/></a></h1>
             {% block content %}
             {% endblock %}
    <!--dentro il blocco verra messo qualunque cosa chimara questo template per far si che venga "completato"-->
    <!--vedi per bene article_list.html-->
         </div>


    </body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>this is the homepage</h1>
    <p>welcome to Djangonautic</p>
</body>
</html>